Repository jrsteensen/OpenHornet, pull requests merged in 2024-07, with the labels that each got.

#1075 Optimize geometry of OH4A1A1-37 Inboard Wall Support
  release/OH4_Left_Console/OH4A1A1 - ASSY, LEFT CONSOLE STRUCTURE/Manufacturing/FDM_OH4A1A1-37_INBOARD WALL SUPPORT_-_V64.3mf
  release/OH4_Left_Console/OH4A1A1 - ASSY, LEFT CONSOLE STRUCTURE/Manufacturing/FDM_OH4A1A1-37_INBOARD WALL SUPPORT_-_V65.3mf
Labels: Type: Enhancement, Category: MCAD, Priority: Low

#1078 Bug comm panel drawing update
  release/OH4_Left_Console/OH4A7A1 - ASSY, COMM PANEL/OH4A7A1-1 - ASSY, COMM PANEL_-_v1.pdf
  release/OH4_Left_Console/OH4A7A1 - ASSY, COMM PANEL/OH4A7A1-1 - ASSY, COMM PANEL_A_v2.pdf
Labels: Type: Bug/Obsolesce, Type: Documentation, Category: MCAD, Priority: Normal

#1050 Fixed typo in readme for knob masks
  release/OHC_Common_Parts/OHC0003 - ASSY, KNOBS/manufacturing/Masks/readme.md
Labels: Type: Documentation, Priority: Normal

#1079 Replaced 2x 2-56 inserts with 0-80 inserts.
  release/OH-MPL - MASTER PARTS LIST, OPENHORNET (FOR REFERENCE ONLY)_-_v9.xlsx
  release/OH-MPL - MASTER PARTS LIST, OPENHORNET (FOR REFERENCE ONLY)_A_v10.xlsx
  release/OH5_Right_Console/OH5A2A4 - ASSY, RADAR ALTIMETER GAUGE/OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE_-_v9.pdf
  release/OH5_Right_Console/OH5A2A4 - ASSY, RADAR ALTIMETER GAUGE/OH5A2A4-1 - ASSY, RADAR ALTIMETER GAUGE_A_v10.pdf
Labels: Type: Bug/Obsolesce, Category: MCAD, Priority: Normal

#1080 OHC0003-A-4RUDGB3 - RUDDER TRIM KNOB: UPDATED INDICA AND FINISH
  release/OHC_Common_Parts/OHC0003 - ASSY, KNOBS/OHC0003 - ASSY, KNOBS_-_v28.pdf
  release/OHC_Common_Parts/OHC0003 - ASSY, KNOBS/OHC0003 - ASSY, KNOBS_A_v29.pdf
Labels: Type: Bug/Obsolesce, Type: Documentation, Category: MCAD, Priority: Normal
